//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenCVApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenCVApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File found {0}.
        /// </summary>
        internal static string FolderIterator_IterateFolderAsync_File_found {
            get {
                return ResourceManager.GetString("FolderIterator_IterateFolderAsync_File_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder found {0}.
        /// </summary>
        internal static string FolderIterator_IterateFolderAsync_Folder_found {
            get {
                return ResourceManager.GetString("FolderIterator_IterateFolderAsync_Folder_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was not identified as image.
        /// </summary>
        internal static string FolderIterator_TestForImage {
            get {
                return ResourceManager.GetString("FolderIterator_TestForImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during matching file {0}.
        /// </summary>
        internal static string ImageMatcher_BeginSearchAsync_Error {
            get {
                return ResourceManager.GetString("ImageMatcher_BeginSearchAsync_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open CV Application file selection.
        /// </summary>
        internal static string SelectFileTitle {
            get {
                return ResourceManager.GetString("SelectFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open CV Application folder selection.
        /// </summary>
        internal static string SelectFolderTitle {
            get {
                return ResourceManager.GetString("SelectFolderTitle", resourceCulture);
            }
        }
    }
}
